apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
  labels:
    app: mi-aplicacion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
        - name: mi-contenedor
          image: ECR_REGISTRY/ECR_REPOSITORY:IMAGE_TAG
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
